# Generated by Django 6.0.4 on 2026-05-04 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicionCorporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('peso', models.FloatField(blank=True, help_text='kg', null=True)),
                ('cintura', models.FloatField(blank=True, help_text='cm', null=True)),
                ('cadera', models.FloatField(blank=True, help_text='cm', null=True)),
                ('pecho', models.FloatField(blank=True, help_text='cm', null=True)),
                ('brazo', models.FloatField(blank=True, help_text='cm', null=True)),
                ('muslo', models.FloatField(blank=True, help_text='cm', null=True)),
                ('notas', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medición Corporal',
                'verbose_name_plural': 'Mediciones Corporales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AnotacionCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('descanso', 'Descanso'), ('planeado', 'Día planeado')], max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones_calendario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anotación de Calendario',
                'verbose_name_plural': 'Anotaciones de Calendario',
                'ordering': ['-fecha'],
                'unique_together': {('usuario', 'fecha')},
            },
        ),
    ]
