# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates',    'templates'),
        ('static',       'static'),
        ('staticfiles',  'staticfiles'),
        ('apps',         'apps'),
        ('sportsvision', 'sportsvision'),
        ('db.sqlite3',   '.'),
        ('db_config.txt','.'),
    ],
    hiddenimports=[
        # Django core
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.auth.backends',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.sessions.backends.db',
        'django.contrib.messages',
        'django.contrib.messages.storage.fallback',
        'django.contrib.staticfiles',
        'django.template.backends.django',
        'django.template.loaders.filesystem',
        'django.template.loaders.app_directories',
        'django.template.context_processors',
        'django.middleware.security',
        'django.middleware.common',
        'django.middleware.csrf',
        'django.middleware.clickjacking',
        'django.core.mail',
        'django.core.mail.backends.smtp',
        'django.core.mail.backends.console',
        # WhiteNoise
        'whitenoise',
        'whitenoise.middleware',
        'whitenoise.storage',
        'whitenoise.compress',
        'whitenoise.responders',
        'whitenoise.string_utils',
        # Apps propias
        'apps.users',
        'apps.users.models',
        'apps.users.views',
        'apps.users.forms',
        'apps.users.backends',
        'apps.users.admin',
        'apps.routines',
        'apps.routines.models',
        'apps.routines.views',
        'apps.routines.forms',
        'apps.routines.admin',
        'apps.routines.templatetags',
        'apps.routines.templatetags.plan_tags',
        'apps.exercises',
        'apps.exercises.models',
        'apps.exercises.views',
        'apps.exercises.admin',
        'apps.exercises.management',
        'apps.exercises.management.commands',
        'apps.exercises.management.commands.seed_exercises',
        'apps.tools',
        'apps.tools.models',
        'apps.tools.views',
        'apps.tools.admin',
        'apps.progress',
        'apps.progress.models',
        'apps.progress.views',
        'apps.progress.admin',
        # PostgreSQL
        'psycopg2',
        'psycopg2._psycopg',
        # Pillow
        'PIL',
        'PIL.Image',
        'PIL.ImageOps',
        # python-dotenv
        'dotenv',
        # twilio (opcional, solo si está instalado)
        # DB
        'django.db.backends.sqlite3',
        'django.db.backends.postgresql',
        # dj-database-url
        'dj_database_url',
        # Otros
        'pkg_resources',
        'random',
        'uuid',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SportsVision',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
