# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['launcher.py'],
    pathex=[],
    binaries=[],
    datas=[('templates', 'templates'), ('static', 'static'), ('staticfiles', 'staticfiles'), ('apps', 'apps'), ('sportsvision', 'sportsvision'), ('db.sqlite3', '.')],
    hiddenimports=[
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'django.template.backends.django',
        'django.template.loaders.filesystem',
        'django.template.loaders.app_directories',
        'django.core.management.commands.runserver',
        'sportsvision.wsgi',
        'sportsvision.settings',
        'sportsvision.urls',
        'apps.users',
        'apps.users.models',
        'apps.users.views',
        'apps.users.urls',
        'apps.routines',
        'apps.routines.models',
        'apps.routines.views',
        'apps.routines.urls',
        'apps.exercises',
        'apps.exercises.models',
        'apps.exercises.views',
        'apps.exercises.urls',
        'apps.tools',
        'apps.tools.models',
        'apps.tools.views',
        'apps.tools.urls',
        'apps.progress',
        'apps.progress.models',
        'apps.progress.views',
        'apps.progress.urls',
        'PIL',
        'psycopg2',
        'whitenoise',
        'whitenoise.middleware',
        'dj_database_url',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SportsVision',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
