# Generated by Django 6.0.4 on 2026-05-03 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('descanso', models.BooleanField(default=False)),
                ('rutina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routines.rutina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_semanal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan del día',
                'verbose_name_plural': 'Plan semanal',
                'unique_together': {('usuario', 'dia')},
            },
        ),
    ]
