# Generated by Django 6.0.4 on 2026-05-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculocaloria',
            options={'ordering': ['-calculado_en'], 'verbose_name': 'Cálculo de Calorías', 'verbose_name_plural': 'Cálculos de Calorías'},
        ),
        migrations.AddField(
            model_name='calculocaloria',
            name='activa',
            field=models.BooleanField(default=False, help_text='Dieta activa del usuario'),
        ),
        migrations.AddField(
            model_name='calculocaloria',
            name='nombre',
            field=models.CharField(blank=True, default='', help_text='Nombre de la dieta', max_length=80),
        ),
    ]
