# Generated by Django 6.0.4 on 2026-05-04 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_alter_calculocaloria_options_calculocaloria_activa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=80)),
                ('activa', models.BooleanField(default=False)),
                ('genero', models.CharField(max_length=1)),
                ('edad', models.PositiveIntegerField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('objetivo', models.CharField(choices=[('perder', 'Perder peso'), ('mantener', 'Mantener peso'), ('ganar', 'Ganar peso')], max_length=20)),
                ('restriccion', models.CharField(choices=[('ninguna', 'Sin restricción'), ('vegetariano', 'Vegetariano'), ('vegano', 'Vegano'), ('sin_gluten', 'Sin gluten'), ('sin_lactosa', 'Sin lactosa')], default='ninguna', max_length=20)),
                ('comidas_dia', models.PositiveIntegerField(default=3)),
                ('calorias_dia', models.FloatField()),
                ('proteinas_g', models.FloatField()),
                ('carbos_g', models.FloatField()),
                ('grasas_g', models.FloatField()),
                ('plan_json', models.JSONField(default=list)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_nutricionales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan Nutricional',
                'verbose_name_plural': 'Planes Nutricionales',
                'ordering': ['-creado_en'],
            },
        ),
    ]
