# Generated by Django 6.0.4 on 2026-05-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='duracion_minutos',
            field=models.PositiveIntegerField(blank=True, help_text='Duración estimada en minutos (sólo para ejercicios de cardio/movilidad)', null=True),
        ),
    ]
