# Generated by Django 6.0.4 on 2026-05-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_seed_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='comentarios',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='errores_comunes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='musculos_antagonistas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='musculos_secundarios',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='variantes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
