# Generated by Django 6.0.4 on 2026-05-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_add_encyclopedia_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='gif_static',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='imagen_static',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
