# Generated by Django 6.0.4 on 2026-05-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('bajar_peso', 'Bajar de peso'), ('mantener_peso', 'Mantener peso'), ('ganar_musculo', 'Ganar músculo'), ('mejorar_resistencia', 'Mejorar resistencia'), ('mejorar_flexibilidad', 'Mejorar flexibilidad'), ('rendimiento', 'Rendimiento deportivo')], default='', max_length=30),
        ),
    ]
