# Generated by Django 6.0.4 on 2026-05-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_objetivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nivel',
            field=models.CharField(choices=[('principiante', 'Principiante'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='principiante', max_length=15),
        ),
    ]
