# Generated by Django 6.0.4 on 2026-05-05 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_limitaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='codigo_pro',
            field=models.CharField(blank=True, default='', help_text='Código único para que usuarios se conecten', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='especialidad',
            field=models.CharField(blank=True, default='', help_text='Ej: Entrenador personal, Nutricionista', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('profesional', 'Profesional / Entrenador')], default='usuario', max_length=15),
        ),
        migrations.CreateModel(
            name='RelacionProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('activa', 'Activa'), ('revocada', 'Revocada por el usuario'), ('rechazada', 'Rechazada por el usuario')], default='pendiente', max_length=12)),
                ('ver_datos_basicos', models.BooleanField(default=True, help_text='Nombre, objetivo, nivel, edad, peso, altura')),
                ('ver_entrenamientos', models.BooleanField(default=True, help_text='Historial de entrenamientos y series')),
                ('ver_mediciones', models.BooleanField(default=False, help_text='Mediciones corporales: peso, grasa, medidas')),
                ('ver_nutricion', models.BooleanField(default=False, help_text='Plan nutricional y calorías')),
                ('ver_salud', models.BooleanField(default=False, help_text='Condiciones de salud y limitaciones (dato sensible)')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_clientes', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_profesionales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relación Profesional-Usuario',
                'verbose_name_plural': 'Relaciones Profesional-Usuario',
                'unique_together': {('profesional', 'usuario')},
            },
        ),
    ]
