# Generated by Django 6.0.4 on 2026-05-05 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profesional_relacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('profesional', 'Profesional / Entrenador'), ('admin_pro', 'Profesional Principal (Admin)')], default='usuario', max_length=15),
        ),
        migrations.CreateModel(
            name='SolicitudProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(help_text='Área de especialización', max_length=120)),
                ('experiencia', models.TextField(help_text='Años de experiencia y formación')),
                ('motivo', models.TextField(help_text='Por qué quiere ser profesional en la plataforma')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=12)),
                ('nota_admin', models.TextField(blank=True, default='', help_text='Nota del Admin Pro al aprobar/rechazar')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud_profesional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Profesional',
                'verbose_name_plural': 'Solicitudes de Profesional',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
