# Generated by Django 6.0.4 on 2026-05-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_email_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_data',
            field=models.TextField(blank=True, default='', help_text='Avatar en base64 (persiste en BD)'),
        ),
    ]
