# Generated by Django 6.0.4 on 2026-05-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_email_pre_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='suspendido_hasta',
            field=models.DateTimeField(blank=True, help_text='Si está establecido, el usuario no puede iniciar sesión hasta esta fecha', null=True),
        ),
    ]
