# Generated by Django 6.0.4 on 2026-05-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_suspendido_hasta'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nota_moderacion',
            field=models.TextField(blank=True, default='', help_text='Razón del baneo o sanción'),
        ),
    ]
