# Generated by Django 6.0.4 on 2026-05-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_mobile_login_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilelogintoken',
            name='is_new_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobilelogintoken',
            name='picture_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
