name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    container:
      image: alvrme/alpine-android:android-34-jdk17

    steps:
      - uses: actions/checkout@v4

      - name: Crear local.properties
        working-directory: android
        run: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - name: Permisos gradlew
        working-directory: android
        run: |
          gradle wrapper --gradle-version=8.4 --no-daemon
          chmod +x gradlew

      - name: Build APK
        working-directory: android
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SportsVision-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
